name: Build assets on release and create archive
on: 
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout master branch'
      uses: actions/checkout@master

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        coverage: pcov

    - name: Get composer cache directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install composer packages
      run: composer install --no-progress

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Add artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: Release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
